name: GitHub Profile Stats

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Tejas2124
          THEME: dark
